name: Publish to PyPI
on:
  push:
    tags:
      - 'v*'

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # REQUIRED for OIDC authentication
      contents: read     # Needed to read repository files
    environment:
      name: pypi
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          pip install build
          python -m build
      - name: Publish distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
